auto: true
safe: true
server: true
server_port: 4000
baseurl: /
url: http://localhost:4000

pygments: true
markdown: maruku
permalink: date
maruku:
    use_tex:    false
    use_divs:   false
    png_engine: blahtex
    png_dir:    images/latex
    png_url:    /images/latex

title: Web4Mobile
description: Platform Independent Mobile Development with Web Technologies
google_analytics: UA-8348928-7
show_downloads: true
theme: jekyll-theme-slate